# Site Settings
baseurl: ""
url : "https://mrqorib.github.io"

# Blog Settings
theme_settings :
  title : M. Reza Qorib
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/square.jpg
    username : M. Reza Qorib
    description : Reza is a postdoctoral fellow at Carnegie Mellon University. He completed his PhD at NUS under Professor Hwee Tou Ng, focusing on system combination and mixtures of experts for grammatical error correction, and continued working as a research fellow on the multilinguality of large language models. He actively contributes to the community through the SEACrowd projects, the ACL Special Interest Group on Southeast Asian NLP (SIGSEA), and by serving as a reviewer for ACL Rolling Review, AAAI, and other NLP conferences and journals.
    email : mrqorib [at] {cmu.edu, u.nus.edu}
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    google_scholar: https://scholar.google.com/citations?user=bSW0QS0AAAAJ&hl=en
    github: mrqorib
    linkedin:  https://linkedin.com/in/rezaqorib 
    gitlab: 
    bitbucket: 
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
